install:
	install -d $(DESTDIR)/usr/lib/perl5/site_perl/OSCAR/
	install -d $(DESTDIR)/usr/lib/perl5/site_perl/OSCAR/PackMan/
	install -m 644 PackMan.pm $(DESTDIR)/usr/lib/perl5/site_perl/OSCAR/
	install -m 644 PackMan/DEB.pm $(DESTDIR)/usr/lib/perl5/site_perl/OSCAR/PackMan/
	install -m 644 PackMan/RPM.pm $(DESTDIR)/usr/lib/perl5/site_perl/OSCAR/PackMan/
